export enum ROUTES {
  // Auth
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',

  // Tabs & Main
  MAIN_TAB = 'MAIN_TAB',
  DASHBOARD = 'DASHBOARD',

  // Attendance
  ATTENDANCE_HOME = 'ATTENDANCE_HOME',
  ATTENDANCE_HISTORY = 'ATTENDANCE_HISTORY',

  // Leave
  LEAVE_OVERVIEW = 'LEAVE_OVERVIEW',
  APPLY_LEAVE = 'APPLY_LEAVE',
  LEAVE_HISTORY = 'LEAVE_HISTORY',

  // Payroll
  PAYSTUB_LIST = 'PAYSTUB_LIST',
  PAYSTUB_DETAILS = 'PAYSTUB_DETAILS',

  // Profile
  PROFILE_HOME = 'PROFILE_HOME',
  EDIT_PROFILE = 'EDIT_PROFILE',

  // Announcements
  ANNOUNCEMENTS = 'ANNOUNCEMENTS',
}
